parameters:
    la_fourchette_pager_duty.factory.event.class: LaFourchette\PagerDutyBundle\Factory\EventFactory
    la_fourchette_pager_duty.reporter.pager_duty.class: LaFourchette\PagerDutyBundle\Reporter\PagerDutyReporter

services:
    la_fourchette_pager_duty.factory.event:
        class: %la_fourchette_pager_duty.factory.event.class%

    # reporters
    la_fourchette_pager_duty.reporter.pager_duty:
        class:        "%la_fourchette_pager_duty.reporter.pager_duty.class%"
        arguments:    [@la_fourchette_pager_duty.factory.event, @logger]
        tags:
            -  { name: liip_monitor.additional_reporter, alias: pagerduty }
