language: php

php:
    - 5.3

env:
  - SYMFONY_VERSION=2.0.*

matrix:
  include:
    - php: 5.3
      env: SYMFONY_VERSION=2.0.*
    - php: 5.3
      env: SYMFONY_VERSION=2.1.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source
  - composer require symfony/console:${SYMFONY_VERSION} --prefer-source
